/*Maps firm order fund codes to selectors; helpful to look at spending organized by person.*/
CASE "Fund Ledger"."Fund Ledger Code" 
	WHEN '1amdf' THEN 'Boling'
	WHEN '1amgf' THEN 'Boling'
	WHEN '1pfmf' THEN 'Boling' 
	WHEN '1pllf' THEN 'De Voe' 
	WHEN '1plnf' THEN 'De Voe'
	WHEN '1penf' THEN 'De Voe'
	WHEN '1pcof' THEN 'De Voe' 
	WHEN '1qcif' THEN 'Dillard'
	WHEN '1jsaf' THEN 'Dillard' 
	WHEN '1jthf' THEN 'Dillard'
	WHEN '1jhcf' THEN 'Fennell' 
	WHEN '1jhef' THEN 'Fennell'
	WHEN '1jpef' THEN 'Fennell' 
	WHEN '1pdaf' THEN 'Harlow'
	WHEN '1pmbf' THEN 'Harlow' 
	WHEN '1pmsf' THEN 'Harlow' 
	WHEN '1pthf' THEN 'Harlow'
	WHEN '1jaaf' THEN 'Jenkins'
	WHEN '1qbif' THEN 'Jones' 
	WHEN '1qchf' THEN 'Jones'
	WHEN '1qphf' THEN 'Jones'
	WHEN '3qbef' THEN 'Jones'
	WHEN '1alif' THEN 'Kohn'
	WHEN '1pfif' THEN 'Kohn' 
	WHEN '1aref' THEN 'Lezenby'
	WHEN '1jpof' THEN 'Lezenby'
	WHEN '1qpsf' THEN 'Lezenby' 
	WHEN '1jhif' THEN 'Lloyd' 
	WHEN '1jlaf' THEN 'Lloyd'
	WHEN '1piaf' THEN 'Lloyd'
	WHEN '1parf' THEN 'Luedke'
	WHEN '1pgrf' THEN 'Luedke'
	WHEN '1qarf' THEN 'Luedke' 
	WHEN '1janf' THEN 'McKinney' 
	WHEN '1jcrf' THEN 'McKinney'
	WHEN '1jguf' THEN 'McKinney'  
	WHEN '1jsof' THEN 'McKinney'
	WHEN '1pclf' THEN 'Rowland' 
	WHEN '1pphf' THEN 'Rowland' 
	WHEN '1prlf' THEN 'Rowland'
	WHEN '1jecf' THEN 'Rowland'
	WHEN '1jbuf' THEN 'Shambaugh'
	WHEN '1jasf' THEN 'Shanley'
	WHEN '1jedf' THEN 'Sipes'
	WHEN '1qeaf' THEN 'Sneff' 
	WHEN '1qmaf' THEN 'Sneff'
	WHEN '1qscf' THEN 'Sneff'  
	WHEN '3qbef' THEN 'Sneff' 
	WHEN '3qeef' THEN 'Sneff' 
	WHEN '3qenf' THEN 'Sneff' 
	WHEN '3qmef' THEN 'Sneff' 
	WHEN '4ambf' THEN 'Thompson' 
	WHEN '4jcpf' THEN 'Thompson' 
	WHEN '4jssf' THEN 'Thompson' 
	WHEN '4phuf' THEN 'Thompson' 
	WHEN '4qhlf' THEN 'Thompson' 
	WHEN '4qscf' THEN 'Thompson' 
	ELSE  'Other' 
END